# Generated by Django 2.0 on 2018-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='status',
            field=models.CharField(default='on', max_length=3),
        ),
        migrations.AddField(
            model_name='alarm',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
