# Generated by Django 2.0 on 2018-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20181116_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(blank=True, default='on', max_length=3),
        ),
    ]
