# Generated by Django 2.1.2 on 2018-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20181116_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
