# Generated by Django 2.1.2 on 2018-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_auto_20181117_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='snooze',
            field=models.IntegerField(default=5),
        ),
    ]
