# Generated by Django 2.1.2 on 2018-11-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_alarm_snooze'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='useUrl',
            field=models.BooleanField(default=False),
        ),
    ]
